//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Activity_Id { get; set; }
        public string Activity_Name { get; set; }
        public string Activity_Location { get; set; }
        public System.DateTime Activity_FromDate { get; set; }
        public System.DateTime Activity_ToDate { get; set; }
        public int Activity_Price { get; set; }
        public bool Booked { get; set; }
        public bool Saved { get; set; }
    }
}
