//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Car_Id { get; set; }
        public string Car_Model { get; set; }
        public string Car_RegisterNumber { get; set; }
        public string Car_Category { get; set; }
        public string Car_Source { get; set; }
        public string Car_Destination { get; set; }
        public System.DateTime Car_FromDate { get; set; }
        public System.DateTime Car_ToDate { get; set; }
        public int Car_Price { get; set; }
        public bool Saved { get; set; }
        public bool Booked { get; set; }
    }
}
