//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Flight_Id { get; set; }
        public string Flight_Name { get; set; }
        public string Flight_Source { get; set; }
        public string Flight_Destination { get; set; }
        public System.TimeSpan Flight_DepartureTime { get; set; }
        public System.TimeSpan Flight_ArrivalTime { get; set; }
        public System.DateTime Flight_DepartureDate { get; set; }
        public System.DateTime Flight_ArrivalDate { get; set; }
        public int Flight_Price { get; set; }
        public bool Booked { get; set; }
        public bool Saved { get; set; }
    }
}
