//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Hotel_Id { get; set; }
        public string Hotel_Name { get; set; }
        public string Hotel_Location { get; set; }
        public System.DateTime Hotel_FromDate { get; set; }
        public System.DateTime Hotel_ToDate { get; set; }
        public int Hotel_Price { get; set; }
        public bool Booked { get; set; }
        public bool Saved { get; set; }
    }
}
